version: '3.8'

services:
  api:
    build: ./api
    container_name: biblioteca_api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    depends_on:
      - db

  site:
    image: nginx:alpine
    container_name: biblioteca_site
    ports:
      - "3000:80"
    volumes:
      - ./site:/usr/share/nginx/html:ro

  db:
    image: postgres:15
    container_name: biblioteca_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
